### ISSUE TITLE
premature message "Code block evaluation complete"

### ISSUE THREAD

**Issue by oystersauce8** [whacked/ob-shstream#1]
Not sure if this package is maintained...
If someone does see this, I want to mention,

emacs says "Code block evaluation complete"
in the minibuffer when the code is only haflway run.

A few other notes
  * the code does go on executing, after the message
  * I have a bash "sleep 50" in the code. Did the sleep fool the elisp in to thinking code finished executing?

My block is like this

```
#+BEGIN_SRC shstream                                                                                             
  set -ev                                                                                                        
  START=$(date +%s)   
```

**Comment by whacked** [comment]
I pushed a fix for a different issue. Don't know if it's related. That said, I cannot repro this issue. Please reopen if persists
