### ISSUE TITLE
Where is insert-string defined?

### ISSUE THREAD

**Issue by adrianparvino** [whacked/ob-shstream#3]

**Comment by adrianparvino** [comment]
https://github.com/emacsorphanage/tail/commit/8254151f7da7a56f4dd99b042c89c0d69b33ff89

**Comment by whacked** [comment]
sorry for the late reply. It looks like `insert-string` was removed since emacs 26.

here's `describe-function` from emacs 25:

```
insert-string is a compiled Lisp function in ‘subr.el’.

(insert-string &rest ARGS)

This function is obsolete since 22.1;
use ‘insert’ instead.

Mocklisp-compatibility insert function.
Like the function ‘insert’ except that any argument that is a number
is converted into a string by expressing it in decimal.

[back]
```

**Comment by whacked** [comment]
it appears to be a single function replacement fix, but I didn't actually test this. Feel free to reopen

**Comment by adrianparvino** [comment]
Self-advertisement, but if you still need ob-shstream, then perhaps look at my fork of ob-session-async? https://github.com/adrianparvino/ob-session-async
